version: "3.7"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn tdl_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/srv/app/api_static
      - media_volume:/srv/app/api_media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    volumes:
      - static_volume:/srv/app/api_static
      - media_volume:/srv/app/api_media
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume:
